{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
  labels:
    {{- include "folio.labels" . | nindent 4 }}
    {{- include "folio.momokayaLabels" . | nindent 4 }}
  annotations:
    {{- include "folio.momokayaAnnotations" . | nindent 4 }}
{{- end }}
