apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: folio-local
servers: 1
agents: 0
registries:
  create:
    name: folio-registry
    host: "127.0.0.1"
    hostPort: "5001"
options:
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
