apiVersion: apps/v1
kind: Deployment
metadata:
  name: folio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: folio
  template:
    metadata:
      labels:
        app: folio
    spec:
      containers:
        - name: folio
          image: folio:latest
          ports:
            - containerPort: 3000
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: folio-secrets
