"""empty message

Revision ID: 1a9aeed14a36
Revises: 
Create Date: 2026-05-22 16:34:16.033536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1a9aeed14a36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banktransactionrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counterparty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('running_balance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key', 'content_hash')
    )
    with op.batch_alter_table('banktransactionrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banktransactionrecord_file_key'), ['file_key'], unique=False)

    op.create_table('invoicerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key', 'content_hash')
    )
    with op.batch_alter_table('invoicerecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoicerecord_file_key'), ['file_key'], unique=False)

    op.create_table('paysliprecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gross_salary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income_tax', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_tax', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('net_pay', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key', 'content_hash')
    )
    with op.batch_alter_table('paysliprecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paysliprecord_file_key'), ['file_key'], unique=False)

    op.create_table('taxreceiptrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_paid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key', 'content_hash')
    )
    with op.batch_alter_table('taxreceiptrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxreceiptrecord_file_key'), ['file_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxreceiptrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxreceiptrecord_file_key'))

    op.drop_table('taxreceiptrecord')
    with op.batch_alter_table('paysliprecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paysliprecord_file_key'))

    op.drop_table('paysliprecord')
    with op.batch_alter_table('invoicerecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoicerecord_file_key'))

    op.drop_table('invoicerecord')
    with op.batch_alter_table('banktransactionrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banktransactionrecord_file_key'))

    op.drop_table('banktransactionrecord')
    # ### end Alembic commands ###
